### ISSUE TITLE
publish doesn't seem to work on your live example

### ISSUE THREAD

**Issue by mateodelnorte** [mitsuruog/what-mqtt#2]

**Comment by mitsuruog** [comment]
hmm, for some reason, WebSocket handshake goes wrong. 

```
WebSocket connection to 'ws://test.mosquitto.org:8080/mqtt' failed: Error during WebSocket handshake: net::ERR_CONNECTION_RESET
```

**Comment by wwj718** [comment]
@mitsuruog  how to solve it ?

**Comment by mitsuruog** [comment]
@wwj718 sorry I have no idea for now. 
I guess `test.mosquitto.org` broker has changed to need some authorization steps. 
if someone would create a PR. I am pretty happy.

**Comment by wwj718** [comment]
just use `ws://broker.hivemq.com:8000/mqtt` 😄 
I create the PR

**Comment by mitsuruog** [comment]
@wwj718 thanks!!
